### ISSUE TITLE
Check for Geant4 support at configure time

### ISSUE THREAD

**Issue by gipert** [BxCppDev/bxdecay0#17]
Hi! Quick one: can I check in `find_package(BxDecay0 ...)` if bxdecay0 was compiled with Geant4 support? I tried with
```cmake
find_package(BxDecay0 1.0 COMPONENTS BxDecay0_Geant4)
```
But `BxDecay0_FOUND` is set to `TRUE` even if I know the `BxDecay0::BxDecay0_Geant4` target is not available in my installation...

**Comment by gipert** [comment]
```cmake
if(NOT TARGET BxDecay0::BxDecay0_Geant4)
  set(BxDecay0_FOUND FALSE)
  ...
endif()
```
can be used as a workaround, even though it would be nicer to register it as a CMake package `COMPONENT`

**Comment by fmauger** [comment]
Hi Luigi
Thanks for the suggestion.
I have modified the CMake config scripts for a very basic support of the COMPONENTS syntax to be used like this:
```find_package(BxDecay0  1.0.9 REQUIRED COMPONENTS Geant4 CONFIG)```
It still needs a few checks but I hope it will suit your needs. Best regards.
I'll tag ASAP.

**Comment by gipert** [comment]
That's great! Thank you for fixing that.

**Comment by fmauger** [comment]
I have just fixed some scripts and now the configuration seems to pass properly when Geant4 component is requested or not.
Let me know if it's ok on your side. Thanks.
