### ISSUE TITLE
Install of BxDecay0 is not relocatable

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/bxdecay0#2]
The current use of resource files in `bxdecay0` makes an install of the package non-relocatable due to the hardcoding of the install prefix:

https://github.com/BxCppDev/bxdecay0/blob/146282677d3acaa30e1fc048d4c9c097befd5df8/source/bxdecay0/resource.cc.in#L38

Whilst something like `binreloc` could be used, it would appear the resource files are

- Very lightweight
- Don't provide data that actually configures the library

With that in mind, could it be easier to directly code these in the `resource.cc` file as static data (or generate the code from the resource files)?

**Comment by fmauger** [comment]
We will also have another use case with the future "2nubb_ga_g0/g2/g22" generators which will probably rely on tabulated two-dimensional (e0,e1) phase spaces built from resource files provided by a theoretician.
Let's wait and see. Laurent, Malak and I are discussing to implement these engines.

**Comment by fmauger** [comment]
As now we have possible additional data for the DB gA process and I have added (tag 1.0.4) the possibility to use the BXDECAY0_PREFIX_DIR env. var. (typically for the DUNE software stack), I think we can now close this issue until some new request about this topic is open.
