### ISSUE TITLE
CMake policy error when checking library component Geant4 with `find_dependency()`

### ISSUE THREAD

**Issue by gipert** [BxCppDev/bxdecay0#20]
Hi! I'm having an issue with BxDecay0 1.0.10 and CMake 3.16.3 which looks related to 8652dbf5a85a37d8a71b2ca7caa8f67fedda0024. 

The situation is the following: I'm developing a library that depends on BxDecay0, and I manage the dependencies with CMake. I call `find_package(BxDecay0 1.0.10 REQUIRED COMPONENTS Geant4)` in the `CMakeLists.txt` of the library project and it works smoothly. But: as I want my library's clients to be able to import it with CMake, I provide a `LibraryConfig.cmake` in which I also check that BxDecay0 is available with `find_dependency(BxDecay0 1.0.10 REQUIRED COMPONENTS Geant4)`, as per [official instructions](https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html?highlight=export%20targets#creating-a-package-configuration-file). For a reason I don't really understand, this step fails with the following when I try to configure a client application that calls `find_package(mylib)`:
```
CMake Warning (dev) at /opt/bxdecay0/lib/cmake/BxDecay0/BxDecay0Config.cmake:69 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/gipert/sw/src/legend/remage/install/lib/cmake/remage/remageConfig.cmake:50 (find_dependency)
  CMakeLists.txt:6 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /opt/bxdecay0/lib/cmake/BxDecay0/BxDecay0Config.cmake:69 (if):
  if given arguments:

    "NOT" "_requested_comp" "IN_LIST" "_BxDecay0_supported_components"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/gipert/sw/src/legend/remage/install/lib/cmake/remage/remageConfig.cmake:50 (find_dependency)
  CMakeLists.txt:6 (find_package)
```
Which refers to [this line here](https://github.com/BxCppDev/bxdecay0/blob/develop/cmake/BxDecay0Config.cmake.in#L55). I don't understand why this happens, as my CMake version should be high enough to have this policy set to "new". More interestingly, the error does not show up when compiling my library and calling `find_package(BxDecay0 REQUIRED COMPONENTS Geant4)`! 

Any ideas from the developers' side?

**Comment by fmauger** [comment]
Hi Luigi,

Strange behaviour indeed. Have you tried to use:
`cmake_policy(SET CMP0057 NEW)`
in your own CMake script ?
Or maybe there is a hidden `cmake_policy(SET CMP0057 OLD)` command somewhere in your CMake setup
and you have not noticed it...
 
In case you cannot make it work with the above ideas, maybe you could modify the BxDecay0Config.cmake script
at line 69 with something like the following (not checked on my side):
```
  list(FIND ${_BxDecay0_supported_components} ${_requested_comp} _found_component_index)
  if (${_found_component_index} EQUAL -1) # Requested component is not supported in this BxDecay0's build
    set(BxDecay0_FOUND False) # So we fail
    set(BxDecay0_NOT_FOUND_MESSAGE "Unsupported component: ${_requested_comp}") # And report
  endif()
```
And please report !

Hope it helps

Regards
frc

**Comment by fmauger** [comment]
I've checked that I request _only_ CMake 3.8 to build  BxDecay0 but in that case I should enforce the 0057 policy to NEW.
So there is an issue on my side to be fixed here. 
Anyway, I wait for your feedback.
Regards
frc

**Comment by gipert** [comment]
> I've checked that I request only CMake 3.8 to build BxDecay0 but in that case I should enforce the 0057 policy to NEW.

This is also what I understand from the docs: https://cmake.org/cmake/help/v3.8/policy/CMP0057.html. Still there's something odd, by the way. I honestly don't get why the error does not show up when calling `find_package()` in `CMakeLists.txt`.

In any case, I just tried adding `cmake_policy(SET CMP0057 NEW)` to [cmake/BxDecay0Config.cmake.in](https://github.com/BxCppDev/bxdecay0/blob/develop/cmake/BxDecay0Config.cmake.in) and it fixes it.

**Comment by gipert** [comment]
Hi, any news on the issue? It's a bit critical for my application. I can open a pull a request if you want.

**Comment by fmauger** [comment]
Hi Luigi

I've read again the doc at https://cmake.org/cmake/help/latest/policy/CMP0057.html and it states:
`This policy was introduced in CMake version 3.3. CMake version 3.21.2 warns when the policy is not set and uses **OLD** behavior. Use the cmake_policy() command to set it to OLD or NEW explicitly.` 

So we should not except this IN_LIST token to be accepted by default in an 'if()'
with a recent version of CMake. 
This is what you face AFAIU.  Anyway, there is something odd which remains with the G4 extension. Probably the policy is forced somewhere in the G4's CMake scripts from the `find_package(Geant4 10.6.3 REQUIRED)`.

For now, I propose to add the  `cmake_policy(SET CMP0057 NEW)` line in the BxDecayConfig.cmake.in file. I'll commit in the dev branch and I'll tag if I get your green light.

**Comment by gipert** [comment]
Hi, thanks a lot for fixing this. I just tested it and and the original issue with my software is solved. Would be great if you could make a new release now!

PS: I packaged bxdecay0 for Arch Linux and uploaded on the Arch User Repositories (AUR): https://aur.archlinux.org/packages/?O=0&K=bxdecay0. I will try to keep them up to date. If you think it's an interesting info for the bxdecay0 user base, you could mention this in the README.

Thanks!

**Comment by fmauger** [comment]
You' re welcome. I'll do it ASAP.
Do you agree if I add the remage project  in the list of supporters and pin its logo ?

**Comment by gipert** [comment]
Sure, no problem! Though the project is still in a super early state now and it's not guaranteed that is will survive the R&D phase ;)

**Comment by fmauger** [comment]
Done at 1.0.11.
