### ISSUE TITLE
Geant4 extension reports error when level = 0

### ISSUE THREAD

**Issue by Berrysoft** [BxCppDev/bxdecay0#22]
https://github.com/BxCppDev/bxdecay0/blob/0bd4505757cb8fe19f4622e9b1b5c2abbb6668bf/extensions/bxdecay0_g4/bxdecay0_g4/primary_generator_action.cc#L72

It should be `(dbd_level < 0)` :)

**Comment by fmauger** [comment]
Good point ! I fix it. Many thanks !
