### ISSUE TITLE
vertex generation in Geant4

### ISSUE THREAD

**Issue by Lowerce** [BxCppDev/bxdecay0#24]
Dear developers,

As your introduction says, bxdecay0 has an interface which allows to install your own algorithm for vertex generation.
And in the example, the way to use your unique_point_vertex_generator is introduced.
But I still don't understand how to write my own vertex generator after inheriting vertex_generator_interface.
Precisely, I do not clearly know how to update my vertex ( for the unique_point_vertex_generator don't need to do this and primary_generator_action uses ShootVertex method to link to vertex generator).
So, I would appreciate it if any vertex generators like random position generation or precomputed points generation which are metioned in the comments of vertex_generator_interface.hh can be provided or described.

Best regards，
Lowerce

**Comment by fmauger** [comment]
Hi Lowerce,
I'm preparing a specific example program with an implementation of a vertex generator based on a Box volume of the G4 geometry... Stay tune !
Regards
frc

**Comment by fmauger** [comment]
There is now a new example named ``bxdecay0_g4_ex02`` (develop branch). 
Please let me know if it helps you as is.
Regards
frc

**Comment by fmauger** [comment]
Example https://github.com/BxCppDev/bxdecay0/tree/develop/extensions/bxdecay0_g4/examples/bxdecay0_g4_ex02 has been updated and now includes a vertex generator class which loads vertex coordinates from a file. See the main program bxdecay0_g4_ex02.cc to activate or not this feature.

**Comment by Lowerce** [comment]
Thanks a lot for your example! 
I learned a lot about vertex generator from your ex02. 

P.S. 
It seems that `AddDaughter` in ` DetectorConstruction.cc` is not needed which causes double `Source` and `SourceHole` in `World` which are shown in Scene tree of Geant4 UI. And maybe some visual settings in vis.mac or Co60.mac should be changed to display the trajectory correctly (I can not use default visual settings to show that in my G4 environment).

Best regards，
Lowerce

**Comment by fmauger** [comment]
I understand that AddDaughter is redundant to declare a daughter physical volume and probably bad practise in new version of G4... so I'll remove it. Thanks for the hint.
Best
frc

**Comment by Lowerce** [comment]
Thanks again for your detailed example about vertex generator ! So I will close this issue now.
And sorry for my ignorance of the feature in early version of Geant4.

Best regards，
Lowerce

**Comment by fmauger** [comment]
You're welcome.
In fact, it was *my* ignorance of new practises in G4.10.X .
Basically, the management of some dynamically objects in G4 craps ("x = new XXX" but no "delete x", and no usage of smart pointers or references which would make things safer). That is not really orthodox programming in terms of memory management sanity and standard OOP practises but we have to live with that!
Regards
frc
