### ISSUE TITLE
Annoying `G4ParticleGun` printouts

### ISSUE THREAD

**Issue by gipert** [BxCppDev/bxdecay0#25]
Hi, I'm not sure whether this should be attributed or not to an incorrect usage of `G4ParticleGun` in the G4 extension, you'll certainly know better than me. I have embedded BxDecay0 in my app at a very basic level, see the relevant source code here:

https://github.com/gipert/remage/blob/master/include/RMGVVertexGenerator.hh
https://github.com/gipert/remage/blob/master/include/RMGGeneratorDecay0.hh
https://github.com/gipert/remage/blob/master/src/RMGGeneratorDecay0.cc

When I test it with a simple 0vbb decay:
```
/bxdecay0/generator/dbd Ge76 2345 1 0
```
My output is flooded by G4 printouts:
```
...
G4ParticleGun::e-
 was defined in terms of KineticEnergy: 0.000887163GeV
 is now defined in terms Momentum: 0.00158237GeV/c
G4ParticleGun::e-
 was defined in terms of KineticEnergy: 0.00115184GeV
 is now defined in terms Momentum: 0.00035327GeV/c
G4ParticleGun::e-
 was defined in terms of KineticEnergy: 0.000110225GeV
 is now defined in terms Momentum: 0.00238566GeV/c
G4ParticleGun::e-
 was defined in terms of KineticEnergy: 0.00192877GeV
 is now defined in terms Momentum: 0.00139113GeV/c
...
```
From `G4ParticleGun::SetParticleMomentum`:

https://github.com/Geant4/geant4/blob/master/source/event/src/G4ParticleGun.cc#L168-L183

That you call here:

https://github.com/BxCppDev/bxdecay0/blob/develop/extensions/bxdecay0_g4/bxdecay0_g4/primary_generator_action.cc#L711

And this is a sort of warning because the particle didn't have zero energy before (?) I'm a bit confused.

**Comment by fmauger** [comment]
Hi gipert,
I'll have a look on this issue ASAP. Stay tuned!
Regards
frc

**Comment by fmauger** [comment]
Hi
As far as I understand, the use of a particle gun instance in a particle loop implies that from the second generated particle, the gun has kept the kinematic values from the former particle (energy, momentum...). Looking at the code in G4ParticleGun.cc, it seems there is no way to reset the former particle data within the gun. The G4ParticleGun::SetInitialValues() could be ok but a) it is protected and  b) it also allocates a messenger without deleting a former one (a design error IMHO!). So a true bad idea !
Maybe I missed something but it seems to me that the only way to proceed would be to inherit a specific gun class... which sounds fool to me. I will have a deeper look in some G4 examples to find a useful hint. 
Regards
frc

**Comment by fmauger** [comment]
Comment: This G4ParticleGun lacks a public ResetParticleData() method...

**Comment by fmauger** [comment]
I have implemented a hack in the develop branch. I would appreciate if you could test if it solved your issue....
Regards
frc

**Comment by gipert** [comment]
Hi @fmauger, thanks for the fix. I don't get the warnings anymore. You can make a new tag, if you wish. For now I think it is fine as it is, in the future you might consider switching to `G4GeneralParticleSource`: https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/html/GettingStarted/eventDef.html#g4generalparticlesource. From a quick look at the source code, it looks like it might fix the issue as well. Thanks again, I'll close this for now.

**Comment by fmauger** [comment]
Ok thanks for the feedback. I'll have a look on the GPS stuff.

**Comment by fmauger** [comment]
and also I'll tag ASAP.
Regards
frc

**Comment by gipert** [comment]
I found this: https://bugzilla-geant4.kek.jp/show_bug.cgi?id=669. Setting the kinetic energy instead of momentum fixes it too.
